### ISSUE TITLE
Kablammo visualization

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/sequenceserver#130]
Would be great to add @jwintersinger 's awesome [kablammo](http://kablammo.wasmuthlab.org) visualisation as an option. If I understand correctly, on the server this would require additional [conversion of blast xml to json](https://github.com/jwintersinger/kablammo/blob/master/data/generate_list.py#L18) and everything else is [client-side javascript](https://github.com/jwintersinger/kablammo/tree/master/js).

**Comment by yeban** [comment]
It seems conversion of XML to JSON isn't required. Kablamo's JSON is simply a listing of all BLAST XML files it should visualize client side. https://github.com/jwintersinger/kablammo/blob/master/data/blast_results.json

**Comment by jwintersinger** [comment]
@yeban is correct. Kablammo uses the XML that BLAST outputs, with no transformation necessary.  The JSON file is only to provide a listing of XML results that Kablammo can request from the server. Provided SequenceServer can make the XML results available via HTTP, loading them into Kablammo should be trivial, since it supports loading results via XMLHttpRequest. See `load_from_server` in [blast_results_loader.js](https://github.com/jwintersinger/kablammo/blob/master/js/blast_results_loader.js).

Thank you, by the way, for the kind words, @yannickwurm -- it's great to see people interested in Kablammo!

**Comment by yeban** [comment]
I would like to see this done on a per hit basis. That is, for each hit the user would choose to see default alignment details or kablammo visualisation. Something like this -
![kablammo_integration](https://cloud.githubusercontent.com/assets/90373/6746893/c94d3576-cef6-11e4-91e1-24b5e785d307.png)

(of course, buttons etc. should be aligned properly, and there needs a way to switch b/w views)

**Comment by yeban** [comment]
Via commits 33e018e and others.
