### ISSUE TITLE
Fails if BLAST+ databases corrupt or incorrect permission on them

### ISSUE THREAD

**Issue by malcook** [wurmlab/sequenceserver#145]
This may be true of other system calls as well, I have not checked.

c.f. https://groups.google.com/d/msgid/sequenceserver/e45e1000-18ea-41d3-92ff-3d16bfda085a%40googlegroups.com.

**Comment by yannickwurm** [comment]
+1 
Thanks @malcook

**Comment by yannickwurm** [comment]
@vivekiitkgp can you catch this?

**Comment by vivekiitkgp** [comment]
@yannickwurm Sure. I'll have a look.

**Comment by yannickwurm** [comment]
Actually this is two parts: 
    1 the specific error.   
    2. Seqserver should have never died in such an ugly manner but should have had a global error catching...

**Comment by yeban** [comment]
I will take care of this @vivekiitkgp.

@malcook,
SequenceServer checks return value of blastdbcmd and everywhere required to the best of my knowledge. It's blastdbcmd that doesn't always exit with non-zero code even on failure. To work around that SequenceServer even checks for error patterns in stderr output. And blastdbcmd isn't consistent even there. So it's just this particular bug that needs to be addressed. Additionally, the error you faced might as well have been due to incorrect permission on some BLAST+ database files instead of corrupt databases. We have discussed this on the mailing list in past and are introducing a check in SequenceServer via #139.

**Comment by malcook** [comment]
Hi - I should have been more specific as to line number.  I just now did a "gem install --pre sequenceserver" in order to see effect of your changes and found that still database.rb line #102  doe not check the return value of blastdbcmd.  This was the line that caused me to report this issue in the first place.
```
        cmd = "blastdbcmd -recursive -list #{database_dir}" \
              ' -list_outfmt "%f	%t	%p	%n	%l	%d" 2>&1'
        list = `#{cmd}`
        list.each_line do |line|
          name = line.split('	')[0]
          next if multipart_database_name?(name)
          self << Database.new(*line.split('	'))
        end
```

my problem was that one of my databases was in some sense corrupt.  I tested and blastdbcmd return code was non-zero in those cases.  

My suggestion is to filter out databases returning non-zero, report them with WARNINGS, and proceed.

**Comment by yeban** [comment]
My changes are not in the gem (pre-) release yet. You can review it here - https://github.com/yannickwurm/sequenceserver/commit/4f2b2dac31f584276d18d50471c6c915ecdd589d#diff-b5971f5d62fc073e2a816e434d3ef905R100. I will announce on ML once I update the gem.

I understand what you are suggesting would be very helpful. I don't think the implementation would be very straightforward though.

**Comment by malcook** [comment]
I see - thanks for clarification - I understand and look forward to this and other changes.

You might consider diffing `blastdbcmd -recursive -list #{database_dir}"` with and without the -list_outfmt .... They _should_ have the same number of lines.

**Comment by yeban** [comment]
Re-opening because of - https://groups.google.com/forum/#!topic/sequenceserver/YWa9ho6SRDk. Looks like 4f2b2da didn't really resolve the issue. ecc1768 proved helpful though.

**Comment by yeban** [comment]
See #192.
