### ISSUE TITLE
must be selfcontained

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/sequenceserver#150]
Following won't work behind firewalls/in closed systems:

```html
  <link href='http://fonts.googleapis.com/css?family=Roboto:400' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
```

**Comment by yeban** [comment]
Instead of serving locally, I would rather use https://github.com/typekit/webfontloader to specify a three second timeout and then fall back to standard Bootstrap fonts.

Serving locally is not as straightforward as it may seem - http://stackoverflow.com/a/13197808, http://michaelboeke.com/blog/2013/09/10/Self-hosting-Google-web-fonts/

**Comment by billzt** [comment]
<a
 class="twitter-share-button"
  href="https://twitter.com/share"
 data-url="http://www.sequenceserver.com" data-text="<%= quote %>" data-via="yeban" data-hashtags="bioinformatics">
 Tweet
</a>

This also didn't work behind firewalls/in closed systems!!!

**Comment by yeban** [comment]
Thanks for the heads up @billzt.

Suggestions anyone how it can be addressed?

**Comment by billzt** [comment]
@yeban I just delete these code. ^_^
