### ISSUE TITLE
New XML format 

### ISSUE THREAD

**Issue by yeban** [wurmlab/sequenceserver#190]
> Date: Tue, May 5, 2015 at 2:32 PM
> Subject: [blast-announce] New Version of BLAST XML output
> To: NLM/NCBI List blast-announce blast-announce@ncbi.nlm.nih.gov
> 
> The NCBI is now making a new version of the BLAST XML available for
> testing.  Read about the changes and how to access BLAST results using
> the new XML at ftp://ftp.ncbi.nlm.nih.gov/blast/documents/NEWXML/xml2.pdf

**Comment by yannickwurm** [comment]
Grrrr their output formats create a bit of a red queen...

* will they support a 'legacy xml' output mode? if not mentioned we should request it. 
* we should restrict support (and downloading) to current blast versions; and probably make a single jump to supporting only the new format when we're ready. Otherwise maintenance is too unpleasant. 
* bio* mailing lists are aware of this and will need to update all of their parsers; probably easiest if we wait for them to implement & piggyback of their re-parsing.

**Comment by yeban** [comment]
I would only request that coverage information be added to XML as well. The split format for instance is good for pagination if there are several queries. I dunno if SequenceServer will make use of it though. I agree about sticking to 2.2.30+ till we are ready and support only the new format thereafter. Updating our own parser will be easier than moving to BioRuby's.

**Comment by yeban** [comment]
2.2.31 seems to support the legacy format still. Not sure till when the legacy XML format will be supported though. In either case, there's some time before we migrate.

**Comment by yeban** [comment]
Support for legacy format has continued until now, and there's no notice (afaik) on when will it be deprecated. Will re-open when necessary.
