### ISSUE TITLE
JSON gem causing installation to fail

### ISSUE THREAD

**Issue by frozflame** [wurmlab/sequenceserver#197]
```
$ sudo gem install sequenceserver
[sudo] password for hailong:
Building native extensions.  This could take a while...
ERROR:  Error installing sequenceserver:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from extconf.rb:1:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/json-1.8.2 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/json-1.8.2/ext/json/ext/generator/gem_make.out
```

**Comment by frozflame** [comment]
I got answer from [Google Group](https://groups.google.com/forum/#!topic/sequenceserver/Link1UCgXrQ):

    sudo apt-get install ruby1.9.1-dev

and had it installed!

**Comment by yeban** [comment]
This is because of the JSON gem trying to install native C extensions. And this gem is needed only on Ruby 1.8.7, but there's no way to specify conditional dependency in gemspec. I think I will be dropping Ruby 1.8.7-1.9.3 support in the next release, but in the meanwhile depending on 'json_pure' instead of 'json' should fix it.
