### ISSUE TITLE
Add query coverage in the default output reports

### ISSUE THREAD

**Issue by billzt** [wurmlab/sequenceserver#199]
"Query coverage" is one of the shown items in the NCBI public BLAST server, and it could also be automatically calculated by BLAST+ command line tools (in -outfmt options). What's more, it is an important score to judge homology. Therefore, it is very necessary to add this items in the default output page.

**Comment by yeban** [comment]
The reason query coverage is currently not included in the HTML report is because coverage info is not present in BLAST's XML output, which we use to generate the HTML report. To get coverage (and taxonomy) info SequenceServer will additionally have to generate and parse tabular output. When this is implemented:

1. Query coverage (`qcov`) should be included in the tabular summary of hits per query.
2. Additionally, per hsp coverage (`qcovhsp`) should be included in HSP stats.

**Comment by billzt** [comment]
@yeban Good idea!
