### ISSUE TITLE
Possible to find out which database a particular hit is coming from?

### ISSUE THREAD

**Issue by terrymun** [wurmlab/sequenceserver#226]
Thanks for the great work, guys (and congratulations on the v1.0.5 release!)

I have to admit that I am working on an edge-case application of SequenceServer, but I am wondering if it is possible to determine which database each hit is coming from, when a user has submitted the query against multiple databases.

Looking into the `search.erb` file, I can see that you are simply looping through the `query.hits` object, with each entry referenced as `hit`. The ID, title, length of the hit, for example, are accessible via `hit.id`, `hit.title` and `hit.length` respectively... however, is it possible to obtain the database where the hit is originating from? I have tried `hit.db`, but I receive an error instead: 

```
NoMethodError - undefined method `db' 
```

It would be nice to be able to also access the database metadata of each hit, like the database name, internally used ID and etc :)

**Comment by yeban** [comment]
You can use `hit.whichdb` for that. Inside of a link generator function you just need to call it as `whichdb`. It returns an Array. If your sequences don't have globally unique ids, the Array may contain more than one element. The Array element(s) are [`Database`](https://github.com/wurmlab/sequenceserver/blob/1.0.x/lib/sequenceserver/database.rb#L22) objects and exposes several metadata about the database.

We chose that name (instead of `db`) because the database the hit came from is not available in the BLAST results, but is computed on demand by checking each querydb for the presence of that id. So there's a cost to calling that function.

**Comment by yeban** [comment]
@terrymun 1.0.5 was tiny release. Just wait for 1.1!

closing - see #228
