### ISSUE TITLE
Including database name in the output

### ISSUE THREAD

**Issue by tomas-pluskal** [wurmlab/sequenceserver#232]
Hi, 

First of all, thanks for developing such a cool blast server!

When we blast against multiple databases, sequenceserver reports the resulting sequence IDs, but not the name of the database. In case the sequence IDs are not human-readable (e.g., as produced by de-novo transcriptome assembly using Trinity), it is not easy to see which database the sequence belongs to. Is there any way to tweak the sequenceserver to include the blast database name in the report?

![screen shot 2015-11-24 at 18 20 02](https://cloud.githubusercontent.com/assets/1796692/11383708/2c1076aa-92d8-11e5-8d7b-062fe0b03c8f.png)

**Comment by yeban** [comment]
Thanks @tomas-pluskal.

This thread likely answers your question - https://groups.google.com/forum/#!topic/sequenceserver/RUOePKmK50g

Do note that BLAST doesn't tell which db a hit came from. And thus `Hit#whichdb` in SequenceServer is a hack. It will work if the sequence ids across dbs. It will return all possible query dbs the hit could have come from if the ids are not unique across dbs.

**Comment by yannickwurm** [comment]
Easiest can be to change the names.
Before creating blastdb, run something like
    ruby -pe 'gsub(/^>/, ">Bombus_terretris.")'  < Trinity.fasta > Trinity.renamed.fasta

That will prepend your species identifier to each sequence id.
We usually also add a version - e.g. _A. Because  we often have to do multiple assemblies....



Typos courtesy of my iPhone

On 24 Nov 2015, at 23:22, Tom?? Pluskal <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

First of all, thanks for developing such a cool blast server!

When we blast against multiple databases, sequenceserver reports the resulting sequence IDs, but not the name of the database. In case the sequence IDs are not human-readable (e.g., as produced by de-novo transcriptome assembly using Trinity), it is not easy to see which database the sequence belongs to. Is there any way to tweak the sequenceserver to include the blast database name in the report?

[screen shot 2015-11-24 at 18 20 02]<https://cloud.githubusercontent.com/assets/1796692/11383708/2c1076aa-92d8-11e5-8d7b-062fe0b03c8f.png>

-

**Comment by tomas-pluskal** [comment]
Thanks, guys!
