### ISSUE TITLE
sequenceserver -b option has no effect

### ISSUE THREAD

**Issue by llozi** [wurmlab/sequenceserver#237]
Hello everybody

I'm trying to run sequenceserver 1.0.6 on a centos7 machine.
I have installed blast+ 2.3.0 to /usr/local/bin but there is an older version of blast (2.2.29) installed
at a different place which is in the system path in front of /usr/local/bin. So I tried to start sequenceserver with the -b option like that:
```
sequenceserver -b /usr/local/bin
```
I get the message "Your BLAST+ version 2.2.29+ is outdated...", meaning it finds the blast version from the $PATH variable.
When I remove the path of the outdated blast version from the $PATH variable, sequenceserver finds the blast version from /usr/local/bin (which is also in $PATH) and everything is fine.

I also changed the value of the bin directory in sequenceserver.conf like this:
```
:bin: /usr/local/bin
```
and started sequenceserver like this:
```
sequenceserver -c <path to config>/.sequenceserver.conf
```
But this has no effect neither.

Didn't I get the intention right of -b option?

Thanks and best regards

**Comment by yeban** [comment]
Both -b command line option and :bin: key in config file work the same. SequenceServer adds the supplied dir to PATH and executes the needed BLAST programs without the absolute path (like you would run ls command). There's a catch here though - if the dir is already in PATH, it won't be added again. You are pointing SequenceServer to /usr/local/bin which is already in PATH. And since the dir containing 2.2.29 is ahead of it in the PATH that's the version that ends up getting used.
