### ISSUE TITLE
document/complete JSON API

### ISSUE THREAD

**Issue by audy** [wurmlab/sequenceserver#250]
I'd like to be able to use sequence server from remote services.

**Comment by astewart-twist** [comment]
This would be an awesome feature, and could simply follow the framework already set out in http://ncbi.github.io/blast-cloud/dev/api.html

**Comment by astewart-twist** [comment]
@yeban , does the fact that you tagged this issue as 'documentation/maintenance' indicate that some kind of json API already does exists?

**Comment by audy** [comment]
Check the 1.0 branch: https://github.com/wurmlab/sequenceserver/tree/1.0.x

**Comment by astewart-twist** [comment]
Thanks @audy, I'll try to install it later.  Is there any way to read what kind of API calls are possible (sans pending documentation)?

**Comment by audy** [comment]
It's still under development and probably will not work.

To check out the endpoints, you'll need to check the [routes](https://github.com/wurmlab/sequenceserver/blob/1.0.x/lib/sequenceserver/routes.rb#L119-L156).

**Comment by astewart-twist** [comment]
Very cool.  This will be neat to see as it develops.

I mentioned it above, but just want to reiterate the suggestion that this API implement the schema used by NCBI at http://ncbi.github.io/blast-cloud/dev/api.html 

I wonder if NCBI's Cloud BLAST API is included in the source code for blast?  If so, maybe the sequenceserver API could just be a pass-through to it?

**Comment by yeban** [comment]
I didn't really think people would be interested: I was going API way only as a better development approach (the codebase is getting bigger). So I am very happy to see the enthusiasm here :).

The API is very simple:
1. To discover available databases - `GET '/searchdata.json'`.
2. To queue a BLAST job - `POST '/'`. Compulsory: `method`, `sequence`, `databases[]`. Optional: `advanced`. As standard POST request. 
3. To poll for results - `GET /:jobid.json`. Returns `202` if not done. Returns results in JSON format if job was completed successfully. Returns `400` if job failed due to incorrect params and `500` if it's a "system error" like corrupt database, BLAST segfaults, out of memory, no space on file system, etc. or a bug in SequenceServer. Error body is returned as HTML instead of JSON and that needs to be fixed.
4. To download results in tsv, xml, etc. formats `GET /download/:jobid.<format>`. Formats are defined in `lib/sequenceserver/blast/constants.rb`. Common: `std_tsv`, `full_tsv`, `xml`.

It works. Except few things will likely change before release, e.g., `advanced` may be renamed to `params`, may combine `/jobid.json` and `/download/:jobid.<format>`, etc.

We won't be adopting NCBI's API. It doesn't make sense to have designated keys for all possible search parameters like evalue, gapopen, etc. or to allow only a limited number of them when our API allows to use all search params (command line options) by specifying them so: `-evalue 1e-5 -num_alignments 10 ...`. Rest is a matter of preference: I like our `/download/:jobid.xml` better than specifying `FORMAT`.

If I remember correctly, NCBI's API is implemented as a perl script not distributed with BLAST+ but you can find it somewhere on the EC2 AMI.

**Comment by PWSmit** [comment]
Hi, 

Is the API still working/ actively supported?  I would love to use sequenceserver via API call, as the AMI versions are not updated/supported.  If so, could you perhaps give an update on how to get things started?

**Comment by yeban** [comment]
Hello,

Yes, [the API described above](#issuecomment-223385758) is supported. We have expanded the capability:

POST 'get_sequences' with `sequence_ids` and `database_ids` to download sequences in FASTA format.

However, we may rename a few things as we get to a stable release.

**Comment by alisahari9** [comment]
Hello, 

I would like to use Flask to POST a JSON on SequenceServer from my Python code, so that I can have my FASTA file blasted against the reference that has been generated. Basically, redirecting the sequencing result to the SequenceServer and seeing the result without having to upload it. I would appreciate your help on this or "any other alternative" you can suggest.

**Comment by yeban** [comment]
Fixed by #473 

The documentation will be available via sequenceserver.com once the changes for version 2.0 are deployed

**Comment by Tinegeldof** [comment]
Hi Yeban. I'm new to this
Related to your answer https://github.com/wurmlab/sequenceserver/issues/250#issuecomment-223385758
Could you provide an example of a POST to do a query based on this text "POST '/'. Compulsory: method, sequence, databases[]" ? In python using requests would even be better. I don't seem to get the arguments right.

Something I tried was 
r = requests.post(url + "/", params=params)
with params = {'method':'blastn', 'sequence':seq, 'databases':['SabDab Antibodies']}
