### ISSUE TITLE
feature request: db admin through web gui

### ISSUE THREAD

**Issue by astewart-twist** [wurmlab/sequenceserver#257]
It'd be really handy to be able to create new databases through the gui.  Correct me if I'm wrong but it appears that the whole application has to be restarted to add new dbs?

**Comment by ar0ch** [comment]
It does need to be restarted but you can automate the entire process. I've put the scripts I use [in this gist](https://gist.github.com/ar0ch/2efb5d86ed3b7165443326cec52f2637)

I use [incron](http://inotify.aiken.cz/?section=incron&page=about&lang=en) to watch for new files in either of the db folders I maintain (genomic and protein) and launch a makeblastdb command and restart sequenceserver on add

**Comment by yeban** [comment]
@ar0ch That is nice! You can also use `yes ^M | sequenceserver -m` to recursively find all new FASTA in the database directory and create BLASTDBs. Sequence type etc will be automatically determined. Would you mind if I add this to the website?

@astewart-twist I think the admin panel should be a community contributed "extension" - I will be happy to help - including a simple but robust authentication scheme so that only admins can access the admin panel.

**Comment by ar0ch** [comment]
@yeban Sure! The `cut -d'/' -f7` should probably be replaced by `basename` for better portability

**Comment by yeban** [comment]
There isn't much to provision in SequenceServer. An admin interface would thus be overkill. I am happy to consider the ability to automatically detect new databases though (#325).
