### ISSUE TITLE
Create milestone for `master`

### ISSUE THREAD

**Issue by audy** [wurmlab/sequenceserver#280]
Current master branch [says](https://github.com/wurmlab/sequenceserver/blob/master/lib/sequenceserver/version.rb) `1.0.4` which is out of date.

Can we get a new milestone to point to the version that master branch is currently headed towards?

That'd make it easier to organize issues related to finishing the API.

**Comment by yeban** [comment]
We are heading towards 1.1. The release will focus on visualisations (happening), bug fixes and some enhancements, and other architectural changes (JSON, job-report, react) already in master. I updated the [1.1 milestone](https://github.com/wurmlab/sequenceserver/milestones/1.1) to reflect this.

If we are to change the number in version.rb, I think it should be set to "dev". Because I don't want to set a version number (even with -pre or -dev suffix) until we are ready to build a gem. I am not very sure though.
