### ISSUE TITLE
Travis Build Failing on master

### ISSUE THREAD

**Issue by nathanhaigh** [wurmlab/sequenceserver#313]
The `README.md` in `master` show Travis builds passing as it is set to show the status of branch `1.0.x` rather than `master`.

Is this intentional? Has anyone looked at why the builds for `master` have been failing for the past 7 months?

**Comment by vivekiitkgp** [comment]
Hi @nathanhaigh 

Yes, this is intentional. The master is the development head of Sequenceserver and is undergoing major changes (scheduled to be released soon). We didn't want `build status` of development branch to confuse people with the status of stable versions.

You can find relevant discussion [here](https://github.com/wurmlab/sequenceserver/issues/222).
