### ISSUE TITLE
Adding links to search hits, "_blank" page

### ISSUE THREAD

**Issue by fikipollo** [wurmlab/sequenceserver#315]
Hi there,

First congratz for the nice tool, it works like a charm!!

I'm adding some custom links  at the results page for local databases installed in my system. 
Following the documentation at http://www.sequenceserver.com/doc/#plugin, I added in the links.rb file:

    def mrs
      url = "/mrs/search?db=all&q=#{id}"
      {
        :order => 3,
        :title => 'MRS',
        :url   => url,
        :icon  => 'fa-external-link'
      }
    end

That works but the link is opened in the same tab and the blast results are lost.
Is it possible to open the external resource in a new tab or window?

thanks!

Rafa

**Comment by vivekiitkgp** [comment]
Hi @fikipollo 

Sequenceserver automatically ensures that _external links_ are opened in new tab. You can see the relevant code [here](https://github.com/wurmlab/sequenceserver/blob/1.0.x/lib/sequenceserver/routes.rb#L62). The reason your results do not open in new tab is because the URI you have, is a relative one. By external, we assumed something that is not present on the same domain.

To fix this, you can simply change the current URI to a full URI (http://...). Let us know if it works!

**Comment by billzt** [comment]
My solution is:
step 1: add a "out-link" class
```
def mrs
  url = "/mrs/search?db=all&q=#{id}"
  {
    :order => 3,
    :title => 'MRS',
    :url   => url,
    :class => 'out-link',
    :icon  => 'fa-external-link'
  }
end
```

step 2: manually edit the `view/result.erb` file: add a JQuery script to add "_blank" attr to all 'out-link' class:
```
<script>
     $(".out-link").attr({"target":"_blank", "title":"Open in new window", "data-toggle":"tooltip"});
</script>
```
