### ISSUE TITLE
sequenceserver --doctor improvements

### ISSUE THREAD

**Issue by yeban** [wurmlab/sequenceserver#320]
- [ ] Check that ids are unique across all databases in databases dir.
- [x] ~~Warn if a protein sequence contains - and * in the sequence.~~ (see #188)
- [ ] Run `--doctor` as part of assisted setup.

**Comment by vivekiitkgp** [comment]
Do you mean id should be unique across all database or a single database. In case of latter, `-parse_seqids` enforcement/check should take care of it.

**Comment by yeban** [comment]
All databases.

**Comment by vivekiitkgp** [comment]
Just a quick question @yeban. I remember in one of our early discussions where having large databases could create potential problems by having to hold a large number of objects in memory (going by the naive way of checking uniqueness -- create sets). Did we arrive at any solution back then? Otherwise, I'll dig for efficient ways to tackle this problem.

**Comment by yeban** [comment]
One idea was to ignore, for e.g., nr database. But would be great if we instead had a solution that scaled to millions of sequence ids, including nr database or for e.g., reads and contigs.

I wonder if bloom filters would be of help here. Maybe ask on KLUG's slack channel for input.

**Comment by yannickwurm** [comment]
ignoring will only work in exceptional cases (e.g. nr). Needs to work. 
  output to unix command line then `| sort | uniq -d` could work  (I think its quite memory efficient)

**Comment by yeban** [comment]
I am retiring this thread. Except for checking uniqueness of ids, all other issues for which we envisioned `--doctor` are accounted for one way or the other.
