### ISSUE TITLE
import blast xml output

### ISSUE THREAD

**Issue by daveb123** [wurmlab/sequenceserver#337]
Hi,
I like the Sequenceserver alignment display. Would it be possible to incorporate an import function to view Blast xml output from commandline blast or from Diamond. There are very few decent xml viewers for this type of data. Of course the download/export features would be disabled.

Also for large data sets the display is very slow and cumbersome. Removing entries with no hits and having an option to display output with alignments collapsed by default would help. Resizing the output properly to larger screens would also help especially with long query names.

The Diamond aligner would be a very useful addition for protein searches and it already outputs in Blast xml format.

**Comment by yannickwurm** [comment]
Thanks @daveb123 
 - those are all valid suggestions. we don't currently have dedicated manpower, so I cannot give you an ETA on any of these. I'll add that we do welcome pull requests :)
 - Regarding DIAMOND, are you sure it now outputs in BLAST xml? A few years ago it wasn't the case (only blast table format) and there were no plans of doing so

**Comment by daveb123** [comment]
Hi Yannick,
Thanks for the response. There is an IT student here at Murdoch University who has 
done some bioinformatics coding before and is interested in this area. He's going to 
have a look and see if he can contribute anything. 

As for Diamond XML output, yes it now does XML, I've used the XML results and 
imported them into other software for further analysis. Here is a web link to the 
diamond wiki (https://wiki.gacrc.uga.edu/wiki/DIAMOND).

Being able to use diamond would be fantastic for all our BlastX analyses which can 
take days.

All the best,

Dave



*Dr Dave Berryman /BSc, PhD/*
*SABC Manager*
*Rm 2.005A | Level 2 | Loneragan Building (Building 235)*
*Murdoch University*
*Tel: 9360 6119*
*Mob: 0405539817*
*Email: D.Berryman@murdoch.edu.au*
*www.sabc.murdoch.edu.au*



> Thanks @daveb123
>  - those are all valid suggestions. we don't currently have dedicated
> manpower, so I cannot give you an ETA on any of these. I'll add that we do
> welcome pull requests :) - Regarding DIAMOND, are you sure it now outputs
> in BLAST xml? A few years ago it wasn't the case (only blast table format)
> and there were no plans of doing so

**Comment by yeban** [comment]
This is happening here - https://github.com/wurmlab/sequenceserver/pull/400

**Comment by daveb123** [comment]
Hi Yannick,

that is fantastic news. I use Sequenceserver regularly for the simpler analyses but I need to use other software for larger data sets and BLASTX-type analyses due to the issues I mentioned. Hopefully this will get me back onto Sequenceserver for the main analyses.



Thanks to the team for the fantastic work.



Dave


[cid:541744745@KDE]

Dr Dave Berryman BSc, PhD

SABC Manager

Rm 2.005A | Level 2 | Loneragan Building (Building 235)

Murdoch University

Tel: 9360 6119

Mob: 0405539817

Email: D.Berryman@murdoch.edu.au

www.sabc.murdoch.edu.au

**Comment by yeban** [comment]
You can test this by installing from git, or keep an eye out for the next release.

**Comment by daveb123** [comment]
Fantastic news. I'll give it a go.



Dave


[cid:1092573789@KDE]

Dr Dave Berryman BSc, PhD

SABC Manager

Rm 2.005A | Level 2 | Loneragan Building (Building 235)

Murdoch University

Tel: 9360 6119

Mob: 0405539817

Email: D.Berryman@murdoch.edu.au

www.sabc.murdoch.edu.au

**Comment by ivopieniak** [comment]
Hi, 
The feature is included in the latest release (2.0 beta). 

To import the XML file simply use this command 
bundler exec bin/sequenceserver --import <absolute path to the file>.

This will return you a uuid number which has to be copied to the browser in this manner:

http://localhost:4567/uuid

Below i attach a screenshots.

![image](https://user-images.githubusercontent.com/44971105/63940548-a1668600-ca61-11e9-9845-c3b0382a767d.png)

![image](https://user-images.githubusercontent.com/44971105/63940811-26ea3600-ca62-11e9-8eaa-618474d8de51.png)

**Comment by nathanweeks** [comment]
Hi @ivopieniak, when I specify only the `--import` option, sequenceserver emits:

```
INFO  Configuration file not found: /home/foo/.sequenceserver.conf
...
Database dir not set.

SequenceServer needs to know where your FASTA files or BLAST+ databases are.
Please enter the path to the relevant directory (default: current directory).

Press Ctrl+C to quit.
```

Does this mean that beforehand another sequenceserver process needs to be started with the `--database_dir` option? When I specify both `--database_dir` and `--import`, sequenceserver emits a job ID and then exits immediately.

**Comment by ivopieniak** [comment]
@nathanweeks 1) The job ID is the desired output of the --import mode, which is pasted in the browser as included in the screenshots.
2) I edited my comment to indicate that after --import there should be an absolute path specified to the existing XML file whether it is generated by BLAST or DIAMOND.
3) Once the import is triggered, the job ID is presented to the user and the XML file is copied over to the sequenceserver directory and can be found under the job ID. 
4) I believe that when it comes to the missing database directory, the SequenceServer requires providing the path to the databases directory in order to get full configuration. However, I am not 100% about that at this very moment. I should be able to give the exact answer to this issue tomorrow. 

I hope this makes things more clear.

**Comment by nathanweeks** [comment]
@ivopieniak: thanks for the clarification.

A little background on my use case:

I have a prototype [Open OnDemand](https://openondemand.org/) [Interactive App](https://osc.github.io/ood-documentation/master/applications/interactive.html) to schedule and run SequenceServer on our HPC cluster. In the web form, the user specifies the --database_dir path and resources for the SLURM job scheduler (wall time, CPUs, and memory), then clicks "submit"; an instance of SequenceSever is scheduled and launched on a compute node, a "connect" button is displayed once an Open OnDemand script detects a listener on the specified TCP port. Once clicked, the user is [taken to a URL based on the compute node host & port](https://osc.github.io/ood-documentation/master/app-development/interactive/view.html#reverse-proxy).

This setup works fine when using SequenceServer for running BLAST. In addition, I'd like to give the user the option to bring their own BLAST XML file generated from a batch job submitted from the command line using the SLURM scheduler, and just use SequenceServer for display. I think requiring both a web form to launch SequenceServer, as well an SSH session where a `sequenceserver --import` command is subsequently run via CLI, is probably too much of a hurdle for many users. It would be more useful if the user could be presented with an (optional) text field in the OOD interactive app form that accepts a pathname (on the HPC cluster file system) of a BLAST XML file they'd like to visualize, and be taken to the resulting job ID page immediately after SequenceServer is launched; it seems this would require the job ID to be known at sequenceserver launch time. Perhaps this could be accomplished if the job ID could be specified via CLI or environment variable?

Sorry if any of this is unclear! Traditional HPC clusters might be more of a niche use case for SequenceServer, but a large volume of bioinformatics is done on them...

**Comment by yannickwurm** [comment]
Hi @nathanweeks  - that is a super cool setup. Does the concept also work for sun grid engine-based HPCs? Once you're happy with it, it would be great if you could share the code - I suspect others in the community would benefit from this!
Yes the way this needs to be accessed at this stage is a bit clunky. 
I suspect that you could get part what you want by making a wrapper that launches Seqserv twice - catching the output. A related workarond may be for us to add a http://hostname/mostrecent url that simply shows the results from the most recent query.  (I don't think this should be activated by default for security/privacy reasons). 
 Ultimately, we will also want to have a good UI element (or even simply drag-and-drop into the normal query page).

**Comment by nathanweeks** [comment]
Hi @yannickwurm , yes, Open OnDemand [supports Grid Engine](https://osc.github.io/ood-documentation/master/installation/resource-manager/sge.html). 

I followed a variant of your suggestion: the first time `sequenceserver` is launched, a symlink is created (`${HOME}/.sequenceserver/results`) that points to the newly-created (job) subdirectory in `${HOME}/.sequenceserver/` (not actually capturing the jobid output of the first sequenceserver process, but rather using "ln -s * results" to match whatever the newly-created directory is via shell pathname expansion -- I can get away with this because the "home directory" is created when the job is launched). Then /results can be used as the URL path. But it should be feasible to capture a jobid & construct a [connection view](https://osc.github.io/ood-documentation/master/app-development/interactive/view.html) based on the jobid; I just need to figure out the OOD plumbing. 

I can certainly make the code for whatever we put into production publicly available.

**Comment by yannickwurm** [comment]
Ha that's an awesome hack @nathanweeks !

**Comment by nathanweeks** [comment]
@yannickwurm : I reworked the prototype SequenceServer Open OnDemand interactive app so that when the user specifies an XML alignment file, the URL is constructed from the captured job ID of the first sequenceserver command per your original recommendation. Also, I added the ability for the user to omit the directory to search for BLAST databases (working around the required --database_dir option) by creating an (almost) empty BLAST database on the fly; something like `printf '>\nA\n' | makeblastdb -dbtype nucl -title empty -out /db/empty`.

I plan to have this app reviewed internally, and can ping you when there's published code.
