### ISSUE TITLE
SequenceServer 1.1.0.beta2 circos plots are missing?

### ISSUE THREAD

**Issue by mictadlo** [wurmlab/sequenceserver#355]
Hi, I just installed SequenceServer 1.1.0.beta2 but circos plots are missing? 

What did I miss?

Thank you in advance,

Michal

**Comment by yeban** [comment]
Hello Michal,

We have temporarily disabled circos. It will return in a future release. We want to first make the new architecture robust. Then we will add back the visualizations.

**Comment by yannickwurm** [comment]
Dear Michal, 
allow me to add a bit more context. We noticed that with queries with large numbers of hits, the time to render the page became too big. Some of the changes Priyam has made in the past weeks will have helped to address this. Additionally, we need to add some extra logic so that the visualizations only occur optionally, or are only dynamically calculated as the user looks at that part of the page. Until that is implemented we do not want to reduce the basic functionality of sequenceserver thus we took the temporary decision to disable the visualisations. 
Cheers and kind regards,
Yannick

**Comment by mictadlo** [comment]
Do you think [p5.js](https://p5js.org/) would be more efficient?

**Comment by yeban** [comment]
Closing as circos was enabled in beta5.

**Comment by mictadlo** [comment]
Hi, I am using beta10 (https://github.com/wurmlab/sequenceserver/issues/366#issuecomment-401351292) but I do not see anywhere circos plots?

**Comment by yeban** [comment]
It's there:

<img width="1162" alt="circos button" src="https://user-images.githubusercontent.com/90373/42143112-6076eb16-7dab-11e8-85c1-8ceb5a5ed690.png">

**Comment by mictadlo** [comment]
Thank you. How could I have not seen
