### ISSUE TITLE
SequenceServer::DATABASE_DIR_NOT_SET: Database dir not set

### ISSUE THREAD

**Issue by mictadlo** [wurmlab/sequenceserver#371]
Hi,
I wrote a [Dockerfile](https://github.com/homonecloco/expvip-web/issues/42) for [expvip-web](https://github.com/homonecloco/expvip-web) which uses sequenceserver. However, I have got `SequenceServer::DATABASE_DIR_NOT_SET: Database dir not set`. 

How is it possible to fix it?

Thank you in advance.

MIchal

**Comment by yeban** [comment]
Database directory can be provided to SequenceServer in two ways: either through a config file or using `-d` option on the command line. Since you are not invoking SequenceServer directly here, config file is probably the only option. Default path for config file is `$HOME/.sequenceserver.conf`.

Since the process is being run inside a docker container, `$HOME` will expand to the home directory of the user running the processes inside the container. Further, the path must exist in the container's file system.

So maybe try creating a config file at the desired location while creating the docker image, which will then be read by SequenceServer during invocation. Since the database path is fixed (I am guessing that's `/data`), you could prepare a config file beforehand and `COPY` or `ADD` to the image. Alternatively, try `RUN sequenceserver -s -d /my/db/path`. Also, `-c` option may be helpful. Please see `sequenceserver --help` for what the options do.
