### ISSUE TITLE
How would one cache the results?

### ISSUE THREAD

**Issue by cghiban** [wurmlab/sequenceserver#399]
Hi,
I would like to cache the results so that blast would not be ran again on the same sequences. This would save a lot of resources. Is this possible at the moment?

Thanks,
Cornel

**Comment by yeban** [comment]
It is possible, but not implemented. We announced a new beta version of SequenceServer last year, which changes the underlying architecture to make advanced features such as the above possible. In the new version, the form data and search results are persisted for a certain number of days (this can be changed through configuration file). Currently, a random unique id is assigned to each submission (job) which is used to retrieve the results once BLAST has completed.

To implement caching, I would first take MD5 hash of the query sequences, list of databases, selected BLAST algorithm, and advanced parameters all put together. Next, I would save this hash as a property on the job object. Then, anytime a new job comes in I would check if a job with the computed MD5 exists (methods are implemented to iterate over and search existing jobs). If a matching job is found, skip creating the new job, and simply return the id of the matching job.

Of course, all this is easier said than done. I would be happy to review code and answer any questions. 

You can read more about the new beta version here - https://groups.google.com/forum/#!msg/sequenceserver/2G4_jdAr4-k/2yxQKixVBQAJ

(it remains a beta because some aspects of the results page are not as polished as I would like, should be fine otherwise)

**Comment by yeban** [comment]
I am closing this as I believe the question has been answered. Just want to add to my answer that SequenceServer 2.0 is stable enough that the community can start building on top of it. See: https://groups.google.com/d/msg/sequenceserver/c98ePBzcuVE/lN-S35jVHgAJ
