### ISSUE TITLE
error when enabling soft mask

### ISSUE THREAD

**Issue by lpoorvin** [wurmlab/sequenceserver#404]
Running 1.1.0.beta12, I am trying to run a search against a protein database that has been masked with segmasker.  Running either a nucleotide or protein sequence with "-db_soft_mask 21" as the advanced parameters immediately brings up a page with only:

> {"message":"Looks like there's a problem with one of the query sequences, selected\ndatabases, or advanced parameters.\n","title":"Input error","more_info":"Option \"-db\" is prohibited."}

I've run searches against this database from CLI blast with softmasking without any problems. 
 
Thanks for any help.

**Comment by yannickwurm** [comment]
Dear Leo,

thank you for the heads up. This is a bug.

for security reasons we disabled the "-db" option.   https://github.com/wurmlab/sequenceserver/blob/45a2718483c055b2c69fb8b1ac76e8669dd11680/lib/sequenceserver/blast/job.rb#L149

It looks like the regular expression we use to catch -db is also catching -db_soft_mask although it shouldn't. 

I'll let priyam/iwo offer a timeline for a fix. However in the short term - if this is for an internal run - I recommend you modify line 149 in job.rb so that it no longer cares about -db

Kind regards, Yannick

**Comment by lpoorvin** [comment]
Hi Yannick,

I'm running locally so I went ahead and made the modification you suggested.  It's working fine now.  Thanks for the quick reply (and the great program)!

Leo

**Comment by yannickwurm** [comment]
Thanks Leo for the kind words!

**Comment by yeban** [comment]
Thanks for reporting the issue. It's now fixed in the source, and will be included in the next release.
