### ISSUE TITLE
query links not shown if >8 queries

### ISSUE THREAD

**Issue by lpoorvin** [wurmlab/sequenceserver#448]
On current release (2.0.0.beta4) running a search with 8 or fewer queries (from fasta file) returns a results page that at the top left has links to the results for each individual query.  If more than 8 queries are used, the results page doesn't include these links.  The actual results are on the page, just the convenient list of links is missing.  Am I missing something obvious?  Is there a way to display the links if >8?  Thanks!

**Comment by yeban** [comment]
You are not missing anything. The index is disabled when there are more than 8 queries. The number is roughly based on the smallest screen I have worked with. It could be a bit higher (like 9 or 10) and with some tweaking of vertical space a little bit more (like 12), but we do need to draw a line at some point otherwise it overshoots the page. Being able to provide an index of clickable links for larger reports will require a design change.

**Comment by yannickwurm** [comment]
Hi @lpoorvin  - thanks for using sequenceserver!
We have considered that when there is a large number of queries, we could also switch to a different user interface element (e.g., a pulldown menu). 

(if you had funds to support the development of this type of feature, please send me a brief email to discuss options)

**Comment by lpoorvin** [comment]
OK, I thought it might be a display issue or similar.  Appreciate the great work on sequenceserver and thanks for the quick replies!  
Leo

**Comment by yeban** [comment]
We increased the limit to 12 queries in 2.0-rc1, thanks to @ivopieniak
