### ISSUE TITLE
Hierarchical display of databases

### ISSUE THREAD

**Issue by michaelbroe** [wurmlab/sequenceserver#459]
In the demo SequenceServer page at: 

https://antgenomes.org/blast/

the databases are divided into two named groups, Nucleotide Databases and Protein Databases. How can I achieve the same effect? 

I have genome, transcriptome, and protein fasta files organized into different subdirectories of the root location specified in .sequenceserver.conf.

When I launched sequence server for the first time, it automatically located and built databases in the first of these subdirectories, but not the other two.

Cheers!
Michael

**Comment by yeban** [comment]
Hi Michael,

Databases are automatically grouped like on antgenomes.org/blast. This may not have happened in your case because for some reasons the FASTA files in the other two subdirectories were not built into databases by SequenceServer. Now I am not sure why that happened, maybe some check failed - we will get to that, but there is a way to force SequenceServer to build all FASTA files into databases.
Could you try running `sequenceserver -m` and let us know if that worked?

**Comment by michaelbroe** [comment]
Thanks for your prompt reply. The fasta files in the other two directories were gzipped. I updated the databases and all is good now.

Thanks again!

**Comment by yeban** [comment]
That's great! Recognising gzipped files is something on our wishlist: #407
