### ISSUE TITLE
2.0 how do you define a proxy route in config

### ISSUE THREAD

**Issue by enuggetry** [wurmlab/sequenceserver#464]
I've setup a proxy for sequenceserver: http://myserver.org/blast (query page works fine)

The hit results come back in the link, such as: 
http://myserver.org/40e56d74-5a57-4012-af39-19ac639c2e67

is there a config options to setup route for "blast"?
http://myserver.org/blast/40e56d74-5a57-4012-af39-19ac639c2e67

Or is this something I need to setup in apache?

**Comment by yeban** [comment]
I think you want to co figure Apache to add / at the end of myserver.com/blast

I think there is a pointer on how to do this on sequenceserver.com/doc (process is the same as for 1.0)

**Comment by yeban** [comment]
That worked?

**Comment by enuggetry** [comment]
@yeban, I haven't had a chance to revisit this.  I will fill you in when I get a chance to hack on it.

**Comment by enuggetry** [comment]
Making the application accessible with Apache2/SSL @ `https://myserver.org/blast.` 

If the application generates new routes, as sequenceserver does, ProxyPassReverse is needed; otherwise; only ProxyPass is needed.
```
<VirtualHost *:443>
  ...
  ProxyPass "/blast/" "http://localhost:4567/"
  ProxyPassReverse "/blast/" "/"
  ...
  SSLCertificate... and any other stuff
  ...
```

**Comment by yeban** [comment]
Thanks for sharing this!

**Comment by loraine-gueguen** [comment]
Hi,

I have setup an Apache proxy for sequenceserver: requests to http://frontendserver.org/context/path/blast are proxied to http://backendserver/project1_blast.

The query page works fine. But the hit results come back with url http://frontendserver.org/a9e21d43-38e8-4a7e-835d-9860c1e769e5 instead of http://frontendserver.org/context/path/blast/a9e21d43-38e8-4a7e-835d-9860c1e769e5

I have defined a ProxyPassReverse directive as stated above, but I cannot make it work.

Do you have an idea, what is wrong ?

The apache proxy config:
```
<VirtualHost *:80>
    ServerName frontendserver.org

<Location /context/path/blast/>
        ProxyPass               http://backendserver/project1_blast/
        ProxyPassReverse        http://backendserver/project1_blast/
</Location>
```

The nginx config on the backend server:
```
server {
    listen 80;
    server_name backendserver;

    location /project1_blast/ {
        proxy_pass http://localhost:4567/;
        proxy_connect_timeout 8;
        proxy_read_timeout 180;
        proxy_intercept_errors on;
    }

    location /project2_blast/ {
        proxy_pass http://localhost:4568/;
        ...
    }
}
```

**Comment by enuggetry** [comment]
have you tried? 
```
        ProxyPass    /context/path/blast/    http://backendserver/project1_blast/
        ProxyPassReverse   /context/path/blast/    /
```
instead of
```
<Location /context/path/blast/>
        ProxyPass               http://backendserver/project1_blast/
        ProxyPassReverse        http://backendserver/project1_blast/
</Location>
```

**Comment by loraine-gueguen** [comment]
>have you tried?
I have tried to change the apache config on the frontend server as you suggested, but there is no change.
I have also tried after stopping the nginx service and the following apache config, but that didn't work either.
```
        ProxyPass    /context/path/blast/    http://backendserver:4567/
        ProxyPassReverse   /context/path/blast/    /
```

**Comment by yeban** [comment]
I wonder if matching Apache's `/context/path/blast/` with Nginx's `/project1_blast/` helps.

I am curious why you have two frontend server when you should be able to get away by proxying requests either from Apache or from Nginx directly to SequenceServer.

**Comment by loraine-gueguen** [comment]
>I wonder if matching Apache's /context/path/blast/ with Nginx's /project1_blast/ helps.
I have tried, but there is always the same error.
>I am curious why you have two frontend server
I have one backend server, only internally accessible, where different sequenceserver interfaces are hosted at different ports ; and I have one backend server, externally accessible, which I wanted to use to proxy requests to the backend server. When connecting directly to the backend server (e.g. http://backendserver:4567/ or http://backendserver/project1_blast/), Sequenceserver 2.0 instances are running well and the results are displayed fine (with url of type http://backendserver/project1_blast/a9e21d43-38e8-4a7e-835d-9860c1e769e5). When connecting to the frontend server, the query page works fine, but the hit results come back with url http://frontendserver.org/a9e21d43-38e8-4a7e-835d-9860c1e769e5 instead of http://frontendserver.org/context/path/blast/a9e21d43-38e8-4a7e-835d-9860c1e769e5

**Comment by yeban** [comment]
Here's another idea: see if you can somehow get Nginx to set 'SCRIPT_NAME' http header when proxying requests to SequenceServer. This should let SequenceServer construct the fully formed URL itself. The value of `SCRIPT_NAME` would be `/context/path/blast/` (not sure if you need leading and trailing slashes).

There is some pointers here that might help, but I don't know if `uwsgi_param` is the right Nginx directive for us: https://stackoverflow.com/questions/57009759/uwsgi-pass-does-not-forward-script-name-header

It might also work to set this header in Apache (in case that is easier) and hopefully Nginx will let it pass through.

To see if SequenceServer is getting this header you can try adding `p env` or `p ENV['SCRIPT_NAME']` in the `call` method in `sequenceserver.rb`.

**Comment by FanchTheSystem** [comment]
Thank you @yeban for your advice and work on this app ;)

I have done some test with @loraine-gueguen , we have tried with SCRIPT_NAME and some other common http header for proxy on both apache and nginx side without succes :(

The issue is on the html form activation to run blast which return an http 303 redirect with the location header stripped (everything after the http://domain/ is removed)

I don't know if this is due to a apache reverse proxy "bug" (as we use an old version) or maybe in your app.

In fact it work well if we do not use 2 reverse proxy (one apache and one nginx) to use only nginx (but maybe it is because there is no relative url translation to be done)

And it does not work either without apache if we try to set some header variable on the nginx side (as mentionned at the beginning of my message)

So I stop writing and give the solution we found.
On the apache side we have add this :

`Header edit Location "(^http[s]?://)([a-zA-Z0-9\.\-]+)(:\d+)?/" "/context/path/blast//`

And it work well now, hoping there will not be any side effect on other redirect in the app

**Comment by lukaszsobala** [comment]
I have something to add, how to configure Apache2 when SequenceServer is not in a subdomain.
One needs to define ProxyPassReverse like so:
`ProxyPassReverse / /`

Otherwise, clicking the BLAST button does not work (the screen turns grey) over https.
