### ISSUE TITLE
link to Apollo

### ISSUE THREAD

**Issue by mictadlo** [wurmlab/sequenceserver#505]
Hi,
I created both a nucledite and protein databes which show up in SequenceServer 1.0.14. From the nucletide database the following code allows me to open Apollo and highlight the region where Blast hit.

```
require 'json'
module SequenceServer
   module Links
       def jbrowse
           qstart = hsps.map(&:qstart).min
           sstart = hsps.map(&:sstart).min
           qend = hsps.map(&:qend).max
           send = hsps.map(&:send).max
           first_hit_start = hsps.map(&:sstart).at(0)
           first_hit_end = hsps.map(&:send).at(0)
           my_features = ERB::Util.url_encode(JSON.generate([{
               :seq_id => accession,
               :start => sstart,
               :end => send,
               :type => "match",
               :subfeatures =>  hsps.map {
                 |hsp| {
                   :start => hsp.send < hsp.sstart ? hsp.send : hsp.sstart,
                   :end => hsp.send < hsp.sstart ? hsp.sstart : hsp.send,
                   :type => "match_part"
                 }
               }
           }]))
           my_track = ERB::Util.url_encode(JSON.generate([
                {
                   :label => "BLAST",
                   :key => "BLAST hits",
                   :type => "JBrowse/View/Track/CanvasFeatures",
                   :store => "url",
                   :glyph => "JBrowse/View/FeatureGlyph/Segments"
                }
           ]))
           url = "https://apollo.nbenth.com/annotator/loadLink" \
                        "?loc=#{accession}:#{first_hit_start-500}..#{first_hit_start+500}" \
                        "&organism=334799" \
                        "&tracks=Annotation-CDS,Annotation%20v3.01,Root%20hist" \
                        "&addFeatures=#{my_features}" \
                        "&addTracks=#{my_track}" \
                        "&highlight=#{accession}:#{first_hit_start}..#{first_hit_end}"
           {
             :order => 2,
             :title => 'Apollo',
             :url   => url,
             :icon  => 'fa-external-link'
           }
       end
   end
end
```
How is it possible to do the same Apollo link for the protein database?

Thank you in advance,

MIchal

**Comment by yeban** [comment]
I am not sure I follow. If against the protein database the query is going to be genomic sequences and you want to link to Jbrowse based on the genomic query, then I suppose you would want to use `query.id` instead of `accession` and `hsp.qend` and `hsp.qstart` instead of `hsp.send` and `hsp.sstart`.

If the query is going to be protein or transcripts, then I think you are better off downloading the matching sequences, realigning them to genome and using those alignments in Jbrowse instead of attempting some complicated coordinate transformation.

Lastly, regardless of the query if you are just looking for a way to open in JBrowse the contig/scaffold/chromsome that the matching protein sequence is annotated on, this information might be there in your in FASTA sequence header, for e.g., '>prot_12345 contig_24819:11456-13180'. You can access the non-id part of FASTA header using the `title` method (e.g., `title.split(':').first`).

**Comment by yeban** [comment]
Did that help?
