### ISSUE TITLE
Incompatible database, why?

### ISSUE THREAD

**Issue by Shellfishgene** [wurmlab/sequenceserver#513]
Hi!
I just installed ver 2 RC8, not sure which version 2 RC I had before (I reinstalled the server). Now it complains many of the databases I use are "incompatible". It reformats them. What excacly is it changing an why?

Thanks for the nice software!

**Comment by yeban** [comment]
This happens if
1. You have a mix of BLAST databases created using BLAST+ >=2.10 and <=2.9 (or 2.8). In such cases, seqserv tries to upgrade databases created using older versions of BLAST. The ones it tells you need formatting are the ones created using older database version.
2. You have databases created without the `-parse_seqids` option of makeblastdb.

I suppose the message displayed by seqserv can improve.

**Comment by Shellfishgene** [comment]
I see, thanks. Creating with ```-parse_seqids``` seems not to be possible if the id is longer than 50 chars. I guess that means I can't use those databases with Sequenceserver anymore? Maybe a future version could also support DBs without ```-parse_seqids```. I guess I could add additional short IDs.

**Comment by yeban** [comment]
We do want to support databases created without `-parse_seqids`. In fact, I had implemented a fix at some point, but the changes required to accommodate the new database format broke it. Ironically, it is also the newer database format that is too strict about the length of sequence ids.

I would ideally like this issue to be addressed by the time we remove the release candidate (rc) tag. In the meantime, you can roll back (`gem uninstall sequenceserver`) or switch to shorter ids indeed.
