### ISSUE TITLE
RC8 - Duplicate WORKDIR line in Dockerfile

### ISSUE THREAD

**Issue by mjy** [wurmlab/sequenceserver#514]
I believe these are duplicates?    I don't think it's being unset b/w them?

https://github.com/wurmlab/sequenceserver/blob/9174a44adccfba3e2bf8fa406d7efdf7ce7794a8/Dockerfile#L9
https://github.com/wurmlab/sequenceserver/blob/9174a44adccfba3e2bf8fa406d7efdf7ce7794a8/Dockerfile#L54

**Comment by yeban** [comment]
I don't think so as they are part of different build stages, and as far as I know WORKDIR is not preserved across build stages.

**Comment by mjy** [comment]
Do you mean WORKDIR is reset at the next  "FROM", not sure if so.

In my clone I removed the second apparently without consequence.

**Comment by yeban** [comment]
Can you check where the source code has been copied to in your image? Is it to `/sequenceserver` or `/`? If it is to `/sequenceserver` then we know WORKDIR is preserved. If it is to `/`, then we know WORKDIR is not preserved, but SequenceServer would still work (because the source-code and the working directory are the same).

**Comment by nathanweeks** [comment]
@yeban is correct, the WORKDIR directive in the earlier build stage is unrelated to the WORKDIR in the later build stage (both build stages independently start in separate ruby:2.7-slim-buster environments, and can even build concurrently until the "final" build stage needs to wait for the completion of the "builder" stage to [copy files from it](https://github.com/wurmlab/sequenceserver/blob/7171c673bf609e0f5d25340362c67b4043b46822/Dockerfile#L37)).

If the [second WORKDIR directive](https://github.com/wurmlab/sequenceserver/blob/9174a44adccfba3e2bf8fa406d7efdf7ce7794a8/Dockerfile#L54) is omitted, the [subsequent COPY directive](https://github.com/wurmlab/sequenceserver/blob/9174a44adccfba3e2bf8fa406d7efdf7ce7794a8/Dockerfile#L57) would copy files from the build context (git working tree) into the root directory of the container (/) instead of at /sequenceserver (e.g., the bin/sequenceserver script would end up in /bin). I haven't tried building sequenceserver that way; it may work, though It's a bit easier to develop & troubleshoot sequenceserver container when its application files are isolated in a separate directory (/sequenceserver).
