### ISSUE TITLE
seqid is modified for some databases

### ISSUE THREAD

**Issue by loraine-gueguen** [wurmlab/sequenceserver#536]
Hi,

The sequence ID displayed on the blast report and available in the sequence retrieved from the webpage is modified (with SequenceServer 2.0.0.rc8)

![image](https://user-images.githubusercontent.com/16136876/127448006-19a86f5e-abb3-4b2e-97e3-5bdadea7e99c.png)

For example:
`gb|KDO35785.1|`  instead of `KDO35785.1` in the source fasta file used to build the database (with makeblastdb): 

```
>KDO35785.1
MTATLGGLSLPGDDPNYFPKLVDQQSPEFLWTGLRGNIVNQVISTDLNYLSVIEYAVKFLKVKHIIVCTKCGGVNAALSQEEFGLVDNWLRSIKDLYIENARKFLGSNPDYDGR
```

It seems to be the case for all databases with GenBank-type identifiers. 

I notice that the two following blastdbcmd queries are successful:

`blastdbcmd -db /db/local/path/Saprolegna-parasitica_proteins_public -entry "KDO35785.1"`

`blastdbcmd -db /db/local/path/Saprolegna-parasitica_proteins_public -entry "gb|KDO35785.1|"`

Is it possible to keep the original identifier (the one given in the source fasta file formatted with makeblastdb) ?

Regards,
Loraine

**Comment by yannickwurm** [comment]
Salut Loraine,
thanks for the message. 
We previously (a few years ago) had a bunch of issues where sequence retrieval wasn't working for some identifiers, which is why we had put in some logic to deal differently with pipes. 

I suspect that blastdbcmd previously had less flexibility than what you are seeing now.

However, I'm unsure whether I've understood your comment correctly.  Are you saying that:
 1. you have a FASTA header  `>KDO35785.1 ...`
 2. you formatted that using SequenceServer (or normal makeblastdb)
 3. it looks like sequenceserver added `gb|` to the identifier?

Or is the reverse whereby 
1. your FASTA header is `>gb|KDO35785.1`
 2. you formatted that using SequenceServer (or normal makeblastdb)
 3. When you click on the hit, the `gb|` has been trimmed?

Thanks again,
Yannick

**Comment by loraine-gueguen** [comment]
Sorry if it was not clear, this is the first case:

1. We have a FASTA header >KDO35785.1 
2. We formatted that using makeblastdb
3. It looks like sequenceserver added `gb|` to the identifier and a trailing pipe

**Comment by yannickwurm** [comment]
Ok - I can confirm that this patterns happens on rc8, and is independent of who formatted the db

**Comment by yeban** [comment]
Hi @loraine-gueguen @yannickwurm 

We have `gb|` in the report because that's the sequence id reported in the XML output of BLAST. However, I do see the original id being reported in the XML as accession.

We used to use accession for both display and sequence retrieval. However, since the move to the new database format, accession no longer works for sequence retrieval in some cases. So I made sequenceserver use id throughout.

It may be possible for us to use accession for display and id for sequence retrieval, which will fix this issue. But I need to be sure that the change will not be a problem for the other id formats (which prompted the move from accession to id in the first place).

If the issue can be fixed in the report, it can be fixed for sequence retrieval as well.

I am at the moment unsure how soon I will be able to look into this. I apologise in advance for the delay.

**Comment by yeban** [comment]
Hello,

I finally had the chance to look into this. If we use accession for display,  it will be an issue for other id types. For example, if the database had a sequence with the following id `gnl|amel|1234`, the HTML report currently displays it correctly, but with the change it will only display `1234`.

How are you managing the issue?  Maybe it is worth writing to NCBI asking why BLAST adds `gb|` to your sequence ids and if there is a way to change or overcome this behaviour?

**Comment by loraine-gueguen** [comment]
Hello @yeban 

Thank you very much for the follow up and for testing the display with accession!

We can handle the issue by using accession in the downloadable report.

> Maybe it is worth writing to NCBI asking why BLAST adds gb| to your sequence ids and if there is a way to change or overcome this behaviour?

yes indeed

Thanks again!

**Comment by loraine-gueguen** [comment]
The answer from NCBI for follow-up:

>Thank you for your question. There is no way around that syntax in the output as long as you are using the *seqid option. But, as you showed, you have the *accn option, and you also have the *acc.ver option.

For example:

```
$blastp -evalue 1e-5 -query query.fasta -db
/path/to/my/db/Saprolegna-parasitica_proteins_public -outfmt '7 sseqid sacc saccver'

# BLASTP 2.9.0+
# Query:
# Database: /path/to/my/db/proteins_blast/Saprolegna-parasitica_proteins_public
# Fields: subject id, subject acc., subject acc.ver
# 6 hits found
gb|KDO35785.1|  KDO35785        KDO35785.1
gb|KDO35767.1|  KDO35767        KDO35767.1
gb|KDO35766.1|  KDO35766        KDO35766.1
gb|KDO35766.1|  KDO35766        KDO35766.1
gb|KDO35502.1|  KDO35502        KDO35502.1
gb|KDO32320.1|  KDO32320        KDO32320.1
# BLAST processed 1 queries

```

In my usecase, only the `saccver` option retrieves the original source id.

**Comment by yannickwurm** [comment]
Ha that's interesting - thanks for the update @loraine-gueguen 

Might you be able to follow-up by asking them whether `saccver` necessarily returns the correct identifier in all cases?

(do we have sufficient test-cases for this in our code?)

**Comment by loraine-gueguen** [comment]
For follow-up, the answer from NCBI about the `saccver` option returning the correct identifier in all cases:

> Yes, whatever is in the definition lines of your blast database.
