### ISSUE TITLE
SequenceServer will not download fasta files

### ISSUE THREAD

**Issue by leogg-github** [wurmlab/sequenceserver#547]
I was using version 1 of SequenceServer and I was getting an error when trying to download fasta sequences from BLAST hits. I followed a thread in the google group (https://groups.google.com/g/sequenceserver/c/-lAwFAvADN0/m/s8jRF2thAAAJ) that said that most problems would be solved by installing the latest version. However I updated the version and the problem persists. Please see error attached.

[blast_issue_101621.txt](https://github.com/wurmlab/sequenceserver/files/7180039/blast_issue_101621.txt)

**Comment by yeban** [comment]
I am guessing you ran makeblastdb yourself and without the `-parse_seqids` option. Unfortunately, FASTA download is not possible (in my understanding) without the `-parse_seqids` option. The next/final 2.0 release of seqserv will either disable the FASTA download link in such cases or other alternatives (e.g., the option to correctly reformat such database) instead of producing an error like above. That's the best we can do.

Please recreate your databases using `-parse_seqids` option of makeblastdb. If your sequence ids are longer than ~50 chars, you will need to find a way to shorten them in a manner that is meaningful to your use case, in order to use the `-parse_seqids` option. I have noticed that a lot of tools that produce really long sequence ids often contain a lot of redundant information that can be easily discarded.

**Comment by leogg-github** [comment]
Thank you so much for your response. I reformatted some of the databases and this worked.

Regards
