### ISSUE TITLE
seqserv reports v5 multipart databases as incompatible and prompts user to reformat them 

### ISSUE THREAD

**Issue by yeban** [wurmlab/sequenceserver#557]

**Comment by yannickwurm** [comment]
Incorrect database detection: db sometimes gets flagged as incompatible even when its fine

occurs if Genbank ids. (because we get 13 files instead of 11)
Or if multipart db.
Likely solution invovles makeblastdb.rb
-> add %v to blastdbcmd listing. To get version - this may be a new option in blast+ 2.12
-> add -removeredundantdb to remove things that are pointed at by an alias
-> potentially discriminate the parse-seqids based on existence of extensions (likely nog nsd nsi for v4 nucleotide), slightly different for others.
