### ISSUE TITLE
Running blast on sequenceserver is very slow

### ISSUE THREAD

**Issue by naity2** [wurmlab/sequenceserver#573]
Hi Team,

Thank you so much for providing `sequenceserver` to the community! It’s awesome!
 
I’m running sequenceserver on an AWS r4 instance and it takes a long time to run a blast against the nt database. I used the following settings with either 32 threads or 4 threads * 8 jobs.

```
- "-task blastn"
- "-evalue 0.05"
- "-word_size 11"
```

I was wondering if you have suggestions on how to make blast run faster?
 
Thanks very much!

**Comment by yeban** [comment]
Do you mean it is slower than running BLAST directly in the command line? Some overhead is to be expected in parsing the results and preparing the HTML report.

**Comment by naity2** [comment]
> Do you mean it is slower than running BLAST directly in the command line? Some overhead is to be expected in parsing the results and preparing the HTML report.

Thank you for your response. I just tested it, and it actually takes a long time to run BLAST directly in the command line as well. It helps if I limit the search to a taxid like `-taxids 9606`. 

I was wondering if you have any other suggestions? Thanks very much for your help!

**Comment by yannickwurm** [comment]
Hi @naity2 

Yes, restricting the search space should have a big impact on speed. 

Other things include: 
 * Can you make the evalue cutoff more strict? (-evalue 1.0e-10) or even 1.0e-20
 * Make the word-size bigger (e.g., NCBI's default megablast for within-species uses word_size 25). 
 * How many results do you need? (perhaps one is enough?) -max_target_seqs 1 
 * If you're only aligning to coding sequences... try doing everything in protein space (blastp) - whether that is relevant depends on your biological question). 
 * Increase RAM so the machine doesn't need to read from disk as much
 * use htop to check that you're not hitting an I/O issue with your disks. This would manifest as a) the machine not using all the cores you've given It, and you would see a "D" (for delay) in the activity column of htop (rather than R for running if I recall correctly). 
 * One *can* also argue for increasing gap penalties as that would make for shorter HSPs (aligning bits), and thus less of the second-stage alignment. However, changing BLAST parameters from default is difficult to do appropriately and thus difficult to defend.

**Comment by naity2** [comment]
> Hi @naity2
> 
> Yes, restricting the search space should have a big impact on speed.
> 
> Other things include:
> 
> * Can you make the evalue cutoff more strict? (-evalue 1.0e-10) or even 1.0e-20
> * Make the word-size bigger (e.g., NCBI's default megablast for within-species uses word_size 25).
> * How many results do you need? (perhaps one is enough?) -max_target_seqs 1
> * If you're only aligning to coding sequences... try doing everything in protein space (blastp) - whether that is relevant depends on your biological question).
> * Increase RAM so the machine doesn't need to read from disk as much
> * use htop to check that you're not hitting an I/O issue with your disks. This would manifest as a) the machine not using all the cores you've given It, and you would see a "D" (for delay) in the activity column of htop (rather than R for running if I recall correctly).
> * One _can_ also argue for increasing gap penalties as that would make for shorter HSPs (aligning bits), and thus less of the second-stage alignment. However, changing BLAST parameters from default is difficult to do appropriately and thus difficult to defend.

Hi @yannickwurm

Thank you so much for your valuable input!

Incorporating your suggestions has improved the search speed. Thank you again for your help!
