### ISSUE TITLE
Sidebar Element Click Causes Exception and User Work Loss

### ISSUE THREAD

**Issue by gorsyan** [wurmlab/sequenceserver#712]
### Issue Overview
When attempting to interact with a sidebar element that is supposed to be non-clickable, it unexpectedly responds to the click. This interaction leads to an exception and subsequently redirects to an error page. This abrupt redirection results in the loss of any unsaved work by the user.

**Comment by yannickwurm** [comment]
Thanks @gorsyan  - can you be more explicit? Make a loom recording?

**Comment by yannickwurm** [comment]
Ok - I've reproduced - thank you for catching this. To reproduce: 
1. hover over FASTA of selected hits.  The pointer changes to a "cannot click" symbol
2. Click anyways

Seqserv receives this click. And errors with "CommandFailed" - likely because the get fasta function was called without the required params (identifiers of sequences).
